# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://keivanzavari.github.io/
baseurl: ""
title: Personal website
author: Keivan Zavari
description: Personal blog and resume
avatar: profile.png
email: keivan dot zavari at sign googlem doot com
github: keivanzavari # username
#twitter: don't have one
linkedin: keivanzavari
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-1


# needed for travis-ci build
exclude: [vendor]
